### PR TITLE
rkahne

### PR DESCRIPTION
**Pull request by rkahne**
I made a bunch of formatting changes to make the doc readable in GitHub, I made changes to terms and term limits, I changed "Chairman" to "President", I removed the existence of the Executive Committee (the board functions as our executive committee), and I finished the document (it ended in the middle of a sentence)

### CODE REVIEW

**Comment by cheapwebmonkey** [comment]
These changes all look good and necessary

**Review by jessetylermullins — APPROVED** [review]

**Review by leighPri — APPROVED** [review]

**Review by bretwalker — APPROVED** [review]
I left a comment on the other PR about substantive changes, but I think these formatting changes look good.

**Review by mgottholsen — APPROVED** [review]
Looks good!

**Review by ehbick01 — APPROVED** [review]

**Review by am1983 — APPROVED** [review]
Looks good to me. We definitely need to talk about our mission as mentioned in Article 4 but that's not relevant to this particular pull request.

**Comment by OrthoStice** [comment]
looks good!

**Comment by thebouv** [comment]
🥇

**Comment by OrthoStice** [comment]
Looks good

**Review by OrthoStice — APPROVED** [review]
Looks Good!

**Review by thebouv — APPROVED** [review]
Pssht, I guess it's okay. For Robert.

**Pull request merged**
