### PR TITLE
added in the org name and ref to Slack voting

### PR DESCRIPTION
**Pull request by cheapwebmonkey**
Testing the tagging of reviewers in this process.

### CODE REVIEW

**Review by mgottholsen — COMMENTED** [review]
35 - Instead of Slack, maybe "electronic messaging"? Don't want to tie it to one specific product.

Should "core members" and or membership be defined in this?

**Comment by ehbick01** [comment]
I think "core members" definitely needs to be as we are using "core" which implies some subjectivity. Defining it is necessary, imo. I'm not sure if "Membership" needs to be since we identify that in the membership guidelines when folks sign on right? Does it need to be xposted in the bylaws?

I agree on Slack being swapped for "electronic messaging"

**Review by jessetylermullins — APPROVED** [review]
Echo changing Slack to "electronic messaging" or "digital communication platform" or something similar. Otherwise looks like a solid set of bylaws to me. Love the emoji additions!

**Review by leighPri — APPROVED** [review]
So far I have nothing more to add. I also agree with changing "Slack" to "electronic messaging." The emojis are great for at-a-glancing commits, I think!

**Review by ehbick01 — APPROVED** [review]
I'm dumb and didn't "officially" review before. This stands as my official review echoing sentiments around Slack -> "electronic messaging".

**Review by rkahne — APPROVED** [review]

**Comment by bretwalker** [comment]
Is this a place where we want to commit to adherence to a code of conduct, even if the CoC is written outside of the bylaws?
There's something about board members being removed for cause with a majority vote. Perhaps we could link the CoC to `cause`.

**Review by bretwalker — COMMENTED** [review]
Is this a place where we want to commit to adherence to a code of conduct, even if the CoC is written outside of the bylaws?
There's something about board members being removed for cause with a majority vote. Perhaps we could link the CoC to cause.

**Review by OrthoStice — APPROVED** [review]

**Comment by mgottholsen** [comment]
Adherence to the CoC should definitely be a requirement, IMO.

**Comment by cheapwebmonkey** [comment]
I have updated the slack to electronic messaging platform and added Core Members. I suggest we open a new branch to hash out these responsibilites and duties further- this is JUST A PLACEHOLDER 😀

**Pull request merged**
